name: add-exe-build-artifacts-to-PR

on:
  workflow_run:
    workflows: ["build-ss3"]
    types:
      - completed
  workflow_dispatch:

jobs:
  artifacts-url-comments:
    name: add artifact links to pull request and related issues job
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' }} && 
      ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number from commit SHA
        id: get_pr
        run: |
          pr_number=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.workflow_run.head_sha }}/pulls" \
            -H "Accept: application/vnd.github.groot-preview+json" | jq '.[0].number')
          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT

      - name: add artifact links to PR and issues
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            prefix: 'Here are the successful executable builds from your PR:'
            format: name
            addTo: pull
            pr: ${{ steps.get_pr.outputs.pr_number }}
