name: add-exe-build-artifacts-to-PR

on:
  workflow_run:
    workflows: ["build-ss3"]
    types:
      - completed
  workflow_dispatch: 

jobs:
  artifacts-url-comments:
    name: add artifact links to pull request and related issues job
    # This 'if' condition ensures the job only runs if the parent workflow was a PR
    # AND that PR has a number (i.e., it's not empty).
    if: |
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.pull_requests[0].number
    runs-on: ubuntu-latest
    steps:
      - name: Get Pull Request Number and Parent Run Details
        id: get_pr_details
        run: |
          # Extract the PR number from the workflow_run event payload.
          PR_NUMBER=$(echo '${{ github.event.workflow_run.pull_requests[0].number }}')
          # Get details about the parent workflow run to construct the artifact URL.
          PARENT_RUN_ID=${{ github.event.workflow_run.id }}
          PARENT_REPO_OWNER=$(echo '${{ github.event.workflow_run.repository.owner.login }}')
          PARENT_REPO_NAME=$(echo '${{ github.event.workflow_run.repository.name }}')
          PARENT_WORKFLOW_ID=${{ github.event.workflow_run.workflow_id }}

          echo "Found PR Number: $PR_NUMBER"
          echo "Parent Run ID: $PARENT_RUN_ID"
          echo "Parent Repo: $PARENT_REPO_OWNER/$PARENT_REPO_NAME"
          echo "Parent Workflow ID: $PARENT_WORKFLOW_ID"

          # Output these values for subsequent steps to use.
          echo "pr_number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
          echo "parent_run_id=$PARENT_RUN_ID" >> "$GITHUB_OUTPUT"
          echo "parent_repo_owner=$PARENT_REPO_OWNER" >> "$GITHUB_OUTPUT"
          echo "parent_repo_name=$PARENT_REPO_NAME" >> "$GITHUB_OUTPUT"
          echo "parent_workflow_id=$PARENT_WORKFLOW_ID" >> "$GITHUB_OUTPUT"

      - name: Get Artifacts List and Generate Direct Download Links
        id: get_artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const run_id = '${{ steps.get_pr_details.outputs.parent_run_id }}';
            const repo_owner = '${{ steps.get_pr_details.outputs.parent_repo_owner }}';
            const repo_name = '${{ steps.get_pr_details.outputs.parent_repo_name }}';

            console.log(`Fetching artifacts for run ID: ${run_id}`);
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: repo_owner,
              repo: repo_name,
              run_id: run_id,
            });

            let artifactLinks = "";
            if (artifacts.data.artifacts.length > 0) {
              artifactLinks += "### Direct Download Links:\n";
              artifacts.data.artifacts.forEach(artifact => {
                // Construct the direct download URL for each artifact
                const downloadUrl = `https://github.com/${repo_owner}/${repo_name}/actions/runs/${run_id}/artifacts/${artifact.id}/zip`;
                artifactLinks += `- [${artifact.name}](${downloadUrl})\n`;
              });
            } else {
              artifactLinks = "No artifacts found for this build run.";
            }

            console.log("Generated Artifact Links:\n" + artifactLinks);
            core.setOutput('artifact_links_markdown', artifactLinks);

      - name: Generate PR Comment Body
        id: generate_comment_body
        run: |
          # Retrieve outputs from previous steps.
          PR_NUMBER=${{ steps.get_pr_details.outputs.pr_number }}
          PARENT_RUN_ID=${{ steps.get_pr_details.outputs.parent_run_id }}
          PARENT_REPO_OWNER=${{ steps.get_pr_details.outputs.parent_repo_owner }}
          PARENT_REPO_NAME=${{ steps.get_pr_details.outputs.parent_repo_name }}
          ARTIFACT_LINKS_MARKDOWN=${{ steps.get_artifacts.outputs.artifact_links_markdown }}

          # Construct the URL to the main workflow run page.
          WORKFLOW_RUN_URL="https://github.com/$PARENT_REPO_OWNER/$PARENT_REPO_NAME/actions/runs/$PARENT_RUN_ID"
          
          # Create the comment body using Markdown.
          COMMENT_BODY="Here are the successful executable builds from your PR:
          
          ${ARTIFACT_LINKS_MARKDOWN}
          
          You can also view the full workflow run details [here]($WORKFLOW_RUN_URL).
          "
          # Output the comment body. Using 'EOF' for multi-line strings.
          echo "comment_body<<EOF" >> "$GITHUB_OUTPUT"
          echo "$COMMENT_BODY" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create or Update PR Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.get_pr_details.outputs.pr_number }}
          body: ${{ steps.generate_comment_body.outputs.comment_body }}
          # Optional: Add a comment identifier if you want to update this specific comment later
          # comment-id: 'artifacts-link-comment'
          # edit-mode: replace # Use 'replace' to update the comment if it already exists